import { formatScore, pvToFigurineSegments, type ScoreLike } from '../stockfish/engineFormat'

/**
 * Builds the small evaluation footer shown under an autogenerated diagram, e.g.:
 *   "SF18: (12.11) 1... ♚e1 2. ♛a7 ♚f1 3. ♛a1+ ♚f2 …"
 *
 * The score is ALWAYS expressed from White's point of view (per product spec),
 * whereas a UCI engine reports it from the side-to-move POV — so it is negated
 * when Black is to move.
 */

export interface DiagramEval extends ScoreLike {
  pv?: string[]
  engineName?: string | null
  depth?: number
}

/** "Stockfish 18" → "SF18", "Stockfish 16.1" → "SF16.1", anything else → "SF". */
export function formatEngineName(name: string | null | undefined): string {
  if (!name) return 'SF'
  const m = name.match(/(\d+(?:\.\d+)?)/)
  return m ? `SF${m[1]}` : 'SF'
}

/** Re-express a side-to-move score from White's POV based on the FEN turn field. */
export function scoreFromWhitePov(score: ScoreLike, fen: string): ScoreLike {
  const isWhiteToMove = (fen.split(' ')[1] ?? 'w') === 'w'
  if (isWhiteToMove) return { ...score }
  const out: ScoreLike = {}
  if (score.scoreCp !== undefined) out.scoreCp = -score.scoreCp
  if (score.mate !== undefined) out.mate = -score.mate
  return out
}

/** Compose the full footer string for a diagram's evaluation. */
export function formatDiagramEvalFooter(evalData: DiagramEval, fen: string): string {
  const prefix = formatEngineName(evalData.engineName)
  const whiteScore = scoreFromWhitePov(
    { scoreCp: evalData.scoreCp, mate: evalData.mate },
    fen,
  )
  const score = formatScore(whiteScore)

  const pv = evalData.pv ?? []
  const segments = pv.length > 0 ? pvToFigurineSegments(fen, pv) : []
  const line = segments.map((s) => s.label).join(' ')

  return line ? `${prefix}: ${score} ${line}` : `${prefix}: ${score}`
}
